version: '3.8'
services:
  postgres:
    image: postgres:latest
    DIContainer_name: postgres
    ports:
      - '6500:5432'
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
volumes:
  postgresDB:

